name: Repository Analysis

on:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run analysis script
        run: |
          chmod +x analysoi.sh
          ./analysoi.sh

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: analysis-report
          path: analysis_report.txt

      - name: Publish report to Github Pages
        run: | 
          cp analysis_report.txt index.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreplay.github.com"
          git add index.txt
          git commit -m "Update analysis report [skip ci]"  || echo "No changes to commit"
          git push origin main


